import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  stepContainer: {
    gap: 2,
    marginBottom: 8,
  },
  reactLogo: {
    backgroundSize: "cover",
    backgroundPosition: "center",
    height: "100%",
    width: "100%",
    position: "absolute",
    top: 0,
    left: 0,
  },
  headerTitleContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 72,
    fontWeight: "900",
    color: "#fff",
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 10,
    letterSpacing: 4,
    textTransform: "uppercase",
  },
  alarm: {
    marginLeft: "10%",
    marginRight: "10%",
    marginTop: 0,
    marginBottom: 5,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  timePickerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  timePicker: {
    width: 100,
    height: 50,
  },
  timePickerSeparator: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#000",
    marginHorizontal: 10,
  },
  alarmInput: {
    fontSize: 25,
    color: "#ccf",
  },
  options: {
    flex: 1,
    marginTop: 0,
    marginBottom: 0,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  addButton: {
    padding: 5,
    color: "pink",
    width: 50,
    height: 50,
    inset: 0,
  },
  addButtonLabel: {
    fontSize: 38,
    fontWeight: "800",
    verticalAlign: "middle",
    textAlign: "center",
    top: 3.5,
  },
  optionsButton: {
    backgroundColor: "#C9EFDD",
    borderColor: "green",
    borderWidth: 1,
    padding: 10,
    width: "120%",
    height: "auto",
  },
  optionsButtonSelected: {
    backgroundColor: "#81b0ff",
    borderColor: "#4169e1",
  },
  optionsButtonSelectedMusic: {
    backgroundColor: "#FFD54F", // amber for music
    borderColor: "#FF9800",
  },
  optionsButtonSelectedSpeech: {
    backgroundColor: "#90CAF9", // light blue for speech
    borderColor: "#1976D2",
  },
  label: {
    fontWeight: "bold",
    textAlign: "center",
  },
  wrapperCustom: {
    borderRadius: 8,
    padding: 6,
  },
  dayContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    marginTop: 5,
    marginBottom: 5,
    paddingHorizontal: 0,
    width: "100%",
  },
  daySection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  recurringSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  dayInput: {
    fontSize: 18,
    color: "#ccf",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    minWidth: 150,
    padding: 5,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    overflow: "hidden",
    minWidth: 150,
    backgroundColor: "#fff",
  },
  picker: {
    height: 50,
    width: 150,
  },
  pickerItem: {
    height: 50,
    fontSize: 16,
  },
  dayButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    minWidth: 150,
  },
  dayButtonText: {
    fontSize: 16,
    color: "#000",
  },
  dayButtonArrow: {
    fontSize: 12,
    color: "#666",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 30,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  doneButton: {
    color: "#007AFF",
    fontSize: 16,
    fontWeight: "600",
  },

  audioList: {
    width: "120%",
    marginTop: 5,
    marginBottom: 10,
    maxHeight: 250,
  },
  audioItem: {
    backgroundColor: "#f0f0f0",
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  audioItemContent: {
    flex: 1,
  },
  audioItemSelected: {
    backgroundColor: "#81b0ff",
  },
  audioLabel: {
    fontSize: 14,
    color: "#333",
  },
  audioLabelSelected: {
    color: "#fff",
    fontWeight: "bold",
  },
  previewButton: {
    backgroundColor: "#4CAF50",
    padding: 8,
    borderRadius: 5,
    minWidth: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  previewButtonText: {
    fontSize: 16,
  },
  saveButton: {
    backgroundColor: "#4CAF50",
    padding: 15,
    width: "120%",
    marginTop: 20,
    borderRadius: 8,
  },
  saveButtonLabel: {
    color: "white",
    fontWeight: "bold",
    fontSize: 18,
    textAlign: "center",
  },
  selectedBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  selectedBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    minHeight: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  selectedBadgeMusic: {
    backgroundColor: "#FFD54F",
  },
  selectedBadgeSpeech: {
    backgroundColor: "#90CAF9",
  },
  selectedBadgeText: {
    fontWeight: "700",
    color: "#111",
  },
});

export default styles;
