import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f0f8ff",
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 6,
    paddingRight: 6,
  },
  timePickerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    overflow: "hidden",
  },
  dayContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    overflow: "hidden",
  },
  androidDayPickerContainer: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    overflow: "hidden",
    minWidth: 130,
    marginRight: 20,
    backgroundColor: "#fff",
  },
  recurringContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  alarmAudioOptions: {
    flex: 1,
    marginTop: 15,
    marginBottom: 0,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 5,
    paddingRight: 50,
    paddingLeft: 50,
    paddingBottom: 0,
  },
  headerImage: {
    width: "100%",
    height: 260,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    overflow: "hidden",
  },
  innerContainer: {
    paddingLeft: 15,
    paddingRight: 15,
  },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  stepContainer: {
    gap: 2,
    marginBottom: 8,
  },
  reactLogo: {
    backgroundSize: "cover",
    backgroundPosition: "center",
    height: "100%",
    width: "100%",
    position: "absolute",
    top: 0,
    left: 0,
  },
  headerTitleContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 72,
    fontWeight: "900",
    color: "#fff",
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 10,
    letterSpacing: 4,
    textTransform: "uppercase",
  },
  alarm: {
    marginLeft: "10%",
    marginRight: "10%",
    marginTop: 0,
    marginBottom: 5,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  timePicker: {
    width: 100,
    height: 50,
  },
  timePickerSeparator: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#000",
    marginHorizontal: 10,
  },
  alarmInput: {
    fontSize: 25,
    color: "#ccf",
  },
  addButton: {
    padding: 5,
    color: "pink",
    width: 50,
    height: 50,
    inset: 0,
  },
  addButtonLabel: {
    fontSize: 38,
    fontWeight: "800",
    verticalAlign: "middle",
    textAlign: "center",
    top: 3.5,
  },
optionsButton: {
  backgroundColor: "#a8e6cf",
  borderColor: "#7fcfa4",
  borderWidth: 0,
  padding: 14,
  width: "120%",
  height: "auto",
  borderRadius: 20,
  shadowColor: "#3d8b5f",
  shadowOffset: { width: 0, height: 6 },
  shadowOpacity: 0.25,
  shadowRadius: 8,
  elevation: 5,
},
  optionsButtonSelected: {
    backgroundColor: "#7fcfa4",
    borderColor: "#5fb88a",
  },
  optionsButtonSelectedMusic: {
    backgroundColor: "#7fcfa4",
    borderColor: "#5fb88a",
  },
  optionsButtonSelectedSpeech: {
    backgroundColor: "#7fcfa4",
    borderColor: "#5fb88a",
  },
  label: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
  },
  dayInput: {
    fontSize: 18,
    color: "#ccf",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    padding: 5,
  },
  dayButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
  },
  dayButtonText: {
    fontSize: 16,
    color: "#000",
  },
  dayButtonArrow: {
    fontSize: 12,
    color: "#666",
  },
  recurringSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  dayPicker: {
    width: 229,
    height: 50,
    overflow: "hidden",
  },
  pickerDropdownItem: {
    height: 50,
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 30,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  doneButton: {
    color: "#007AFF",
    fontSize: 16,
    fontWeight: "600",
  },
  audioList: {
    width: "120%",
    overflow: "scroll",
    marginTop: 8,
    marginBottom: 0,
    maxHeight: 105,
    borderRadius: 16,
  },
  audioItem: {
    backgroundColor: "#fff",
    padding: 12,
    marginBottom: 6,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#3d8b5f",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  audioItemContent: {
    flex: 1,
  },
  audioItemSelected: {
    backgroundColor: "#7fcfa4",
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  audioLabel: {
    fontSize: 16,
    color: "#2c3e50",
    fontWeight: "500",
  },
  audioLabelSelected: {
    color: "#fff",
    fontWeight: "700",
  },
  previewButton: {
    backgroundColor: "#a8e6cf",
    padding: 8,
    borderRadius: 10,
    minWidth: 40,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#3d8b5f",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
  },
  previewButtonText: {
    fontSize: 16,
  },
  saveButton: {
    backgroundColor: "#5fb88a",
    padding: 18,
    width: "120%",
    marginTop: 8,
    borderRadius: 20,
    shadowColor: "#3d8b5f",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  saveButtonLabel: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 18,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  saveButtonDisabled: {
    backgroundColor: "#d4d4d4",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  saveButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  saveButtonLabelDisabled: {
    color: "#9e9e9e",
  },
  selectedBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  selectedBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    minHeight: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  selectedBadgeMusic: {
    backgroundColor: "#FFD54F",
  },
  selectedBadgeSpeech: {
    backgroundColor: "#90CAF9",
  },
  selectedBadgeText: {
    fontWeight: "700",
    color: "#111",
  },
});

export default styles;
