name: Expo Dev Build & Distribute

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  setup-and-install:
    name: "Bootstrap and install"
    runs-on: ubuntu-latest

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN}}
      EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      TESTERS: ${{ vars.TESTERS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js and PNPM
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable and activate pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@8.15.5 --activate
          pnpm -v
      - name: Install dependencies
        run: pnpm install
  install-jq:
    name: "Install JQ"
    runs-on: ubuntu-latest
    needs: setup-and-install
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
  authenticate:
    name: "Authenticate"
    runs-on: ubuntu-latest
    needs: install-jq
    steps:
      - name: Authenticate with Expo
        run: pnpm exec eas whoami || pnpm exec eas login
  build-and-download:
    name: "Build and Download"
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
      - name: Trigger EAS Android build
        id: eas-build-android
        run: |
          eas build --platform android --profile development --non-interactive --json > build-result-android.json 2>/dev/null
          BUILD_URL=$(jq -r '.[0].artifacts.buildUrl' < build-result-android.json)
          echo "BUILD_URL=$BUILD_URL" >> $GITHUB_ENV
      - name: Download APK
        run: |
          curl -L -o app-dev.apk "$BUILD_URL"
  upload:
    name: "Upload to Firebase"
    runs-on: ubuntu-latest
    needs: build-and-download
    steps:
      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app-dev.apk \
            --app "$FIREBASE_APP_ID" \
            --testers "$TESTERS" \
            --release-notes "Auto-uploaded build from GitHub Actions on $(date +'%Y-%m-%d %H:%M')"
            - name: Notify Slack of build status
            if: always()  # runs even if previous steps fail
            env:
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
              GITHUB_COMMIT_SHA: ${{ github.sha }}
              GITHUB_COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
            run: |
              if [ "${{ job.status }}" == "success" ]; then
                STATUS_EMOJI=":white_check_mark:"
                STATUS_TEXT="Build succeeded"
              else
                STATUS_EMOJI=":x:"
                STATUS_TEXT="Build failed"
              fi

              PAYLOAD=$(jq -n \
                --arg text "$STATUS_EMOJI $STATUS_TEXT for commit <$GITHUB_COMMIT_URL|${GITHUB_COMMIT_SHA::7}>." \
                --arg details "See workflow run: <$GITHUB_RUN_URL|here>" \
                '{text: "\($text)\n\($details)"}')

              curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK_URL"
  slack:
    name: "Notify Slack"
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Notify Slack of build status
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
          GITHUB_COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        run: |
          if [ "${{ job.status }}" == "success" ]; then
          STATUS_EMOJI=":white_check_mark:"
          STATUS_TEXT="Build succeeded"
          else
          STATUS_EMOJI=":x:"
          STATUS_TEXT="Build failed"
          fi

          PAYLOAD=$(jq -n \
          --arg text "$STATUS_EMOJI $STATUS_TEXT for commit <$GITHUB_COMMIT_URL|${GITHUB_COMMIT_SHA::7}>." \
          --arg details "See workflow run: <$GITHUB_RUN_URL|here>" \
          '{text: "\($text)\n\($details)"}')

          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK_URL"
