name: Distribute Preview Build

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  GITHUB_COMMIT_SHA: ${{ github.sha }}
  GITHUB_COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  TESTERS: ${{ vars.TESTERS }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  deploy-android:
    uses: ./.github/workflows/deploy-android-preview.yml
    secrets:
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      TESTERS: ${{ vars.TESTERS }}

  deploy-ios:
    uses: ./.github/workflows/deploy-ios-preview.yml
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_APP_ID: ${{ secrets.ASC_APP_ID }}
